version: "3.9"
services:
   postgresql:
     image: postgres:15.1
     environment:
       POSTGRES_DB: eshop
       POSTGRES_USER: eshop
       POSTGRES_PASSWORD: test123
     ports:
      - 5432:5432
     volumes:
       - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
