version: "3.9"
services:
  postgresql:
    image: postgres:15.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: test123
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: {}
